#!/usr/bin/env bash

source $HOME/.secrets/loopia-api

api_loopia_url="https://api.loopia.se/RPCSERV"

### addSubdomain ###
#    args: domain subdomain
#  output: "OK" || "Error: ... "
# example: addSubdomain example.com www 

addSubdomain () {
        curl -s -H 'Content-Type: text/xml' -d \
                "<methodCall><methodName>addSubdomain</methodName>\
                        <params><param><value><string>$api_loopia_user</string></value></param>\
                        <param><value><string>$api_loopia_pass</string></value></param>\
                        <param><value><string>$1</string></value></param>\
                        <param><value><string>$2</string></value></param></params>\
                </methodCall>" $api_loopia_url
}


### addZoneRecordA ###
#    args: subdomain domain type ttl rdata
#  output: "OK" || "Error: ... "
# example: addZoneRecord domain subdomain 3600 93.184.216.34

addZoneRecordA () {
        curl -s -H 'Content-Type: text/xml' -d \
                "<methodCall><methodName>addZoneRecord</methodName>\
                        <params>\
                                <param><value><string>$api_loopia_user</string></value></param>\
                                <param><value><string>$api_loopia_pass</string></value></param>\
                                <param><value><string>$1</string></value></param>\
                                <param><value><string>$2</string></value></param>\
                                <param><value><struct>\
                                        <member><name>type</name><value><string>A</string></value></member>\
                                        <member><name>ttl</name><value><int>$3</int></value></member>\
                                        <member><name>rdata</name><value><string>$4</string></value></member>\
                                </struct></value></param>\
                        </params>\
                </methodCall>" $api_loopia_url
}


### domainIsFree ###
#    args: domain
#  output: "OK" || "Error: ... "
# example: domainIsFree example.com

domainIsFree () {
        curl -s -H 'Content-Type: text/xml' -d \
                "<methodCall><methodName>domainIsFree</methodName>\
                        <params>\
                                <param><value><string>$api_loopia_user</string></value></param>\
                                <param><value><string>$api_loopia_pass</string></value></param>\
                                <param><value><string>$1</string></value></param>\
                        </params>\
                </methodCall>" $api_loopia_url \
                | xmllint --xpath "//methodResponse/params/param/value/string/text()" -
}


